### ISSUE TITLE
request to update to Alamofire 4.8.X

### ISSUE THREAD

**Issue by piemonte** [Svrf/svrf-swift4-client#2]
Hey SVRF,

Excited to integrate your services. I was incorporating your library and found I'm using a newer version of Alamofire than this library.

Would this be feasible to update?

```sh
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "Alamofire":
  In Podfile:
    Alamofire (= 4.8.1)

    SVRFClient (~> 1.3.1) was resolved to 1.3.1, which depends on
      Alamofire (~> 4.5.0)

Specs satisfying the `Alamofire (= 4.8.1), Alamofire (~> 4.5.0)` dependency were found, but they required a higher minimum deployment target.
```

✌️

**Comment by brentchow** [comment]
Thanks for reporting!

Closed by: https://github.com/Svrf/svrf-swift4-client/commit/725ae5c1cfd2333d68c6a21cf8cf6ec5d7928a28
